version: "3.3"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    # healthcheck:
    #         test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    #         timeout: 20s
    #         retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: lavagna
      
    volumes:
      - db:/var/lib/mysql
  app:
    image: 651733321730.dkr.ecr.us-east-1.amazonaws.com/abigail:lavagna-1.7
    depends_on:
      - mysqldb
    links:
      - mysqldb
    restart: on-failure
    ports:
      - 8080:8080
  webserver:
    image: nginx
    depends_on:
      - app
    links:
      - app
    restart: on-failure
    ports:      
          - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./target/lavagna/:/usr/share/nginx/html/
  docserver:
    image: nginx
    depends_on:
      - app
    links:
      - app
    restart: on-failure
    ports:
          - 8081:80
    volumes:
      - ./target/lavagna/help/:/usr/share/nginx/html/



volumes:
  db:

